[project]
name = 'full house'
description = 'Demonstrates a basic fungible token that conforms to the SIP-010 FT standard'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP1AJVMEGSMD6QCSZ1669Z5G90GEHVK2MEM7J0AHH.fullhouse'

[contracts.fullhouse]
path = 'contracts/fullhouse.clar'
clarity_version = 4
epoch = "latest"

[contracts.defi]
path = 'contracts/extern/defi.clar'
clarity_version = 4
epoch = "latest"

